/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 05:36:13 GMT 2024
 */

package com.axios.core.config.global;

import org.junit.Test;
import static org.junit.Assert.*;
import com.axios.core.config.global.HttpGlobalConfig;
import java.net.CookieManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpGlobalConfig_ESTest extends HttpGlobalConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpGlobalConfig.timeout = 0;
      int int0 = HttpGlobalConfig.getTimeout();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpGlobalConfig.setTimeout(464);
      int int0 = HttpGlobalConfig.getTimeout();
      assertEquals(464, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpGlobalConfig.setCookieManager((CookieManager) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CookieManager cookieManager0 = HttpGlobalConfig.getCookieManager();
      assertNotNull(cookieManager0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = HttpGlobalConfig.getTimeout();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HttpGlobalConfig.closeCookie();
      CookieManager cookieManager0 = HttpGlobalConfig.getCookieManager();
      assertNull(cookieManager0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      HttpGlobalConfig httpGlobalConfig0 = new HttpGlobalConfig();
      assertEquals((-1), HttpGlobalConfig.timeout);
  }
}
