/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 05:11:00 GMT 2024
 */

package com.axios.core.tool.regular;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.axios.core.tool.regular.RegularTool;
import java.nio.CharBuffer;
import java.util.function.Consumer;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegularTool_ESTest extends RegularTool_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("Akt;t5", (-750));
      String string0 = RegularTool.get(pattern0, (CharSequence) "Akt;t5", 0);
      assertEquals("Akt;t5", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("");
      // Undeclared exception!
      try { 
        RegularTool.get(pattern0, (CharSequence) "", (-764));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // No group -764
         //
         verifyException("java.util.regex.Matcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("T_xB+XI%", (-3959));
      Consumer<Matcher> consumer0 = (Consumer<Matcher>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      RegularTool.get(pattern0, (CharSequence) "T_xB+XI%", consumer0);
      assertEquals((-3959), pattern0.flags());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("");
      Consumer<Matcher> consumer0 = (Consumer<Matcher>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      RegularTool.get(pattern0, (CharSequence) "", consumer0);
      assertEquals("", pattern0.pattern());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("com.axios.core.tool.regular.RegularTool", (-290));
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      String string0 = RegularTool.get(pattern0, (CharSequence) charBuffer0, (-883));
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("");
      RegularTool.get(pattern0, (CharSequence) "", (Consumer<Matcher>) null);
      assertEquals("", pattern0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StringBuffer stringBuffer0 = new StringBuffer("");
      RegularTool.get((Pattern) null, (CharSequence) stringBuffer0, (Consumer<Matcher>) null);
      assertEquals("", stringBuffer0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Consumer<Matcher> consumer0 = (Consumer<Matcher>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      RegularTool.get((Pattern) null, (CharSequence) null, consumer0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("");
      String string0 = RegularTool.get(pattern0, (CharSequence) "Kcza", 0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      StringBuffer stringBuffer0 = new StringBuffer("");
      String string0 = RegularTool.get((Pattern) null, (CharSequence) stringBuffer0, 0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = RegularTool.get((Pattern) null, (CharSequence) null, 0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      RegularTool regularTool0 = new RegularTool();
  }
}
