/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 05 02:02:56 GMT 2024
 */

package com.axios.core.config.ssl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import com.axios.core.config.ssl.TrustAnyHostnameVerifier;
import javax.net.ssl.SSLSession;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TrustAnyHostnameVerifier_ESTest extends TrustAnyHostnameVerifier_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SSLSession sSLSession0 = mock(SSLSession.class, new ViolatedAssumptionAnswer());
      TrustAnyHostnameVerifier trustAnyHostnameVerifier0 = new TrustAnyHostnameVerifier();
      boolean boolean0 = trustAnyHostnameVerifier0.verify((String) null, sSLSession0);
      assertTrue(boolean0);
  }
}
