/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 05 01:13:47 GMT 2024
 */

package com.axios.response;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.axios.core.config.global.GlobalCookieManager;
import com.axios.core.connection.Connection;
import com.axios.response.HttpResponse;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.OutputStream;
import java.net.CookieManager;
import java.net.CookieStore;
import java.net.HttpCookie;
import java.net.Proxy;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpResponse_ESTest extends HttpResponse_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpResponse httpResponse1 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpResponse httpResponse2 = httpResponse1.sync();
      assertSame(httpResponse1, httpResponse2);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      HttpResponse httpResponse1 = httpResponse0.sync();
      assertEquals((-1), httpResponse1.getStatus());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpResponse httpResponse1 = new HttpResponse(connection0, (Charset) null, true, true);
      int int0 = httpResponse1.getStatus();
      assertEquals(200, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, ".)W?n'hwlb%OZ;");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      MockFile mockFile0 = new MockFile(".)W?n'hwlb%OZ;", ".)W?n'hwlb%OZ;");
      File file0 = httpResponse0.completeFileNameFromHeader(mockFile0);
      assertFalse(file0.canRead());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, false);
      MockFile mockFile0 = new MockFile("    ");
      File file0 = httpResponse0.completeFileNameFromHeader(mockFile0);
      assertSame(mockFile0, file0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      connection0.connect();
      FileSystemHandling.shouldAllThrowIOExceptions();
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      MockFile mockFile0 = new MockFile("    ");
      // Undeclared exception!
      try { 
        httpResponse0.writeBodyForFile(mockFile0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.IOException: Simulated IOException
         //
         verifyException("com.axios.core.tool.file.FileTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBodyForFile((File) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // [targetFileOrDir] must be not null!
         //
         verifyException("com.axios.core.assertion.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("HTTP");
      byte[] byteArray0 = new byte[4];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody("HTTP/1.0");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.FileNotFoundException
         //
         verifyException("com.axios.core.tool.file.FileTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // [targetFileOrDir] must be not null!
         //
         verifyException("com.axios.core.assertion.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, false);
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream((OutputStream) null);
      MockPrintStream mockPrintStream0 = new MockPrintStream(bufferedOutputStream0);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((OutputStream) mockPrintStream0, true);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, true, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((OutputStream) null, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // [out] must be not null!
         //
         verifyException("com.axios.core.assertion.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      File file0 = MockFile.createTempFile("M:o[K1PF", "HTTP/1.1");
      FileSystemHandling.shouldAllThrowIOExceptions();
      // Undeclared exception!
      try { 
        httpResponse0.writeBody(file0, "");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.IOException: Simulated IOException
         //
         verifyException("com.axios.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((File) null, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // [targetFileOrDir] must be not null!
         //
         verifyException("com.axios.core.assertion.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      FileSystemHandling.shouldAllThrowIOExceptions();
      MockFile mockFile0 = new MockFile("    ");
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection0, charset0, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((File) mockFile0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.IOException: Simulated IOException
         //
         verifyException("com.axios.core.tool.file.FileTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((File) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // [targetFileOrDir] must be not null!
         //
         verifyException("com.axios.core.assertion.Assert", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      CookieManager cookieManager0 = mock(CookieManager.class, new ViolatedAssumptionAnswer());
      doReturn((CookieStore) null).when(cookieManager0).getCookieStore();
      GlobalCookieManager.setCookieManager(cookieManager0);
      // Undeclared exception!
      try { 
        httpResponse0.getCookieValue("HTTP/1.1");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.axios.core.config.global.GlobalCookieManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.contentLength();
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, true, true);
      // Undeclared exception!
      try { 
        httpResponse0.completeFileNameFromHeader((File) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.axios.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = null;
      try {
        httpResponse0 = new HttpResponse((Connection) null, charset0, false, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.axios.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      httpResponse0.close();
      assertFalse(httpResponse0.isOk());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, true, true);
      List<HttpCookie> list0 = httpResponse0.getCookies();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      String string0 = httpResponse0.contentEncoding();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      boolean boolean0 = httpResponse0.isDeflate();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      MockFile mockFile0 = new MockFile("HTTP/1.1", "");
      // Undeclared exception!
      try { 
        httpResponse0.writeBody((File) mockFile0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      boolean boolean0 = NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, false);
      boolean boolean1 = httpResponse0.isGzip();
      assertFalse(boolean1 == boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = null;
      try {
        httpResponse0 = new HttpResponse(connection0, charset0, false, true);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not find: www.someFakeButWellFormedURL.org
         //
         verifyException("com.axios.response.HttpResponse", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, false);
      File file0 = MockFile.createTempFile("M:o[K1PF", "HTTP/1.1");
      File file1 = httpResponse0.completeFileNameFromHeader(file0);
      assertFalse(file1.isDirectory());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      String string0 = httpResponse0.toString();
      assertEquals("Response Headers: \r\nResponse Body: \r\n    null\r\n", string0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
        try {
          URL uRL0 = MockURL.getHttpExample();
          Connection connection0 = Connection.create(uRL0, (Proxy) null);
          EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
          NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
          HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
          File file0 = MockFile.createTempFile("M:o[K1PF", "HTTP/1.1");
          // Undeclared exception!
          try { 
            httpResponse0.writeBody(file0, "=?ve#C,,oC7");
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.io.FilePermission\" \"/tmp/M:o[K1PF0HTTP/1.1.=?ve#C,,oC7\" \"delete\")
             // java.lang.Thread.getStackTrace(Thread.java:1564)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkDelete(SecurityManager.java:1007)
             // sun.nio.fs.UnixPath.checkDelete(UnixPath.java:807)
             // sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:222)
             // sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
             // java.nio.file.Files.delete(Files.java:1126)
             // com.axios.core.tool.file.FileTool.delFile(FileTool.java:276)
             // com.axios.core.tool.file.FileTool.del(FileTool.java:126)
             // com.axios.response.HttpResponse.writeBody(HttpResponse.java:362)
             // sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
             // sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
             // java.lang.reflect.Method.invoke(Method.java:498)
             // org.evosuite.testcase.statements.MethodStatement$1.execute(MethodStatement.java:257)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.MethodStatement.execute(MethodStatement.java:220)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:750)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
        } catch(Throwable t) {
            // Need to catch declared exceptions
        }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      String string0 = httpResponse0.body();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      // Undeclared exception!
      try { 
        httpResponse0.bodyStream();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      String string0 = httpResponse0.getCookieValue("HTTP/1.1");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      boolean boolean0 = httpResponse0.isOk();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      connection0.responseCode();
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      boolean boolean0 = httpResponse0.isOk();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      boolean boolean0 = httpResponse0.isOk();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, false, true);
      String string0 = httpResponse0.getCookieStr();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      MockFile mockFile0 = new MockFile("HTTP/1.1");
      // Undeclared exception!
      try { 
        httpResponse0.writeBodyForFile(mockFile0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      int int0 = httpResponse0.getStatus();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      // Undeclared exception!
      try { 
        httpResponse0.writeBody("HTTP/1.0");
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpCookie httpCookie0 = httpResponse0.getCookie("");
      assertNull(httpCookie0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      byte[] byteArray0 = httpResponse0.bodyBytes();
      assertNull(byteArray0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      boolean boolean0 = httpResponse0.isChunked();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "    ");
      HttpResponse httpResponse0 = null;
      try {
        httpResponse0 = new HttpResponse(connection0, (Charset) null, false, false);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Long", e);
      }
  }
}
