/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 05:34:27 GMT 2024
 */

package com.axios.core.tool.text;

import org.junit.Test;
import static org.junit.Assert.*;
import com.axios.core.tool.text.ArrayIter;
import java.util.Iterator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IterableIter_ESTest extends IterableIter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      ArrayIter<Object> arrayIter0 = new ArrayIter<Object>(objectArray0);
      Iterator<Object> iterator0 = arrayIter0.iterator();
      assertNotNull(iterator0);
  }
}
