/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 05 02:06:06 GMT 2024
 */

package com.axios.header;

import org.junit.Test;
import static org.junit.Assert.*;
import com.axios.header.Header;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Header_ESTest extends Header_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Header header0 = new Header();
      Header header1 = header0.add("", "");
      Map<String, String> map0 = header1.getHeaders();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Header header0 = new Header();
      Map<String, String> map0 = header0.getHeaders();
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Header header0 = new Header();
      Header header1 = header0.add("N%$Nr>?q", "");
      assertSame(header1, header0);
  }
}
