/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 12 05:07:32 GMT 2024
 */

package com.axios.core.strem;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.axios.core.connection.Connection;
import com.axios.core.strem.HttpInputStream;
import com.axios.response.HttpResponse;
import java.io.IOException;
import java.net.Proxy;
import java.net.URL;
import java.nio.charset.Charset;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.evosuite.runtime.testdata.EvoSuiteURL;
import org.evosuite.runtime.testdata.NetworkHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpInputStream_ESTest extends HttpInputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      httpResponse0.status = 400;
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      long long0 = httpInputStream0.skip(0L);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      byte[] byteArray0 = new byte[2];
      int int0 = httpInputStream0.read(byteArray0, (int) (byte)2, (int) (byte)0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      byte[] byteArray0 = new byte[3];
      long long0 = httpInputStream0.skip(3786L);
      assertEquals(35L, long0);
      
      int int0 = httpInputStream0.read(byteArray0, (int) (byte)1, (int) (byte)0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      long long0 = httpInputStream0.skip(404);
      assertEquals(35L, long0);
      
      int int0 = httpInputStream0.read();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      boolean boolean0 = httpInputStream0.markSupported();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      long long0 = httpInputStream0.skip(404);
      assertEquals(35L, long0);
      
      int int0 = httpInputStream0.available();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      httpInputStream0.close();
      try { 
        httpInputStream0.skip(9223372036854775807L);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.util.ByteDataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      try { 
        httpInputStream0.reset();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // mark/reset not supported
         //
         verifyException("org.evosuite.runtime.util.ByteDataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      httpInputStream0.close();
      try { 
        httpInputStream0.read();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.util.ByteDataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HttpInputStream httpInputStream0 = null;
      try {
        httpInputStream0 = new HttpInputStream((HttpResponse) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.axios.core.strem.HttpInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      httpResponse0.status = 0;
      HttpInputStream httpInputStream0 = null;
      try {
        httpInputStream0 = new HttpInputStream(httpResponse0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Could not find: www.someFakeButWellFormedURL.org
         //
         verifyException("com.axios.core.strem.HttpInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      httpInputStream0.close();
      try { 
        httpInputStream0.available();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.util.ByteDataInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      HttpResponse httpResponse0 = new HttpResponse(connection1, (Charset) null, false, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      // Undeclared exception!
      try { 
        httpInputStream0.read((byte[]) null, 404, 404);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      httpInputStream0.mark(200);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      httpInputStream0.reset();
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      int int0 = httpInputStream0.available();
      assertEquals(35, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = new Connection(uRL0, (Proxy) null);
      Connection connection1 = connection0.connect();
      Charset charset0 = Charset.defaultCharset();
      HttpResponse httpResponse0 = new HttpResponse(connection1, charset0, true, true);
      byte[] byteArray0 = new byte[5];
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      // Undeclared exception!
      try { 
        httpInputStream0.read(byteArray0, (int) (byte) (-30), (int) (byte) (-30));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.ByteArrayInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      int int0 = httpInputStream0.read();
      assertEquals(38, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      Connection connection0 = Connection.create(uRL0, (Proxy) null);
      EvoSuiteURL evoSuiteURL0 = new EvoSuiteURL("http://www.someFakeButWellFormedURL.org/fooExample");
      NetworkHandling.createRemoteTextFile(evoSuiteURL0, "&/dYTM=");
      HttpResponse httpResponse0 = new HttpResponse(connection0, (Charset) null, true, true);
      HttpInputStream httpInputStream0 = new HttpInputStream(httpResponse0);
      boolean boolean0 = httpInputStream0.markSupported();
      assertFalse(boolean0);
  }
}
